version: '3.8'

services:
  # SERVICIO 1: Base de Datos (MySQL)
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: bettsoft
      MYSQL_ROOT_PASSWORD: root
    ports:

      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # SERVICIO 2: Tu Backend (FastAPI)
  backend:
  build: ./backend/backend
  ports:
    - "8000:8000"
  depends_on:
    - db
  environment:
    DATABASE_URL: "mysql+pymysql://root:root@db:3306/bettsoft"


volumes:
  mysql_data: